name: dio_azure_application_insights_interceptor
description: A Dio interceptor to submit telemetry data to Azure Application Insights
version: 0.0.1
repository: https://github.com/evoleen/dio_azure_application_insights_interceptor
environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  azure_application_insights: ^4.0.1
  dio: ^5.7.0
  http: ^1.2.2
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
