name: dio_azure_application_insights_interceptor
description: A Dio interceptor to submit telemetry data to Azure Application Insights
version: 0.0.6
repository: https://github.com/evoleen/dio_azure_application_insights_interceptor
environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  azure_application_insights: ^5.0.0
  dio: ^5.7.0
  http: ^1.2.2
  uuid: ^4.5.1
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
